### ISSUE TITLE
Generate code & zarr collections to make BRAN2020 U & V "analysis ready" for CARSv2

### ISSUE THREAD

**Issue by Thomas-Moore-Creative** [CARSv2/cars-v2#13]
# Generate code & zarr collections to make BRAN2020 U & V "analysis ready" for CARSv2

U & V will be needed for using `DIVAnd`'s "advection constraint.

[Advection constraint](https://docs.juliahub.com/DIVAnd/AaVxY/2.6.5/#Advection-constraint)

> The functions DIVAndrun, DIVAndgo and diva3d can also use an advection constraint forcing the analysis to align with a vector field (e.g. a velocity field). The velocity field should be a tuple of n-elements. Every element of the tuple is a gridded array (defined at the same location than the target array) representing a single velocity component. For 3D analysis, the order of the dimensions is typically: longitude, latitude and depth. Like-wise the velocity components are zonal, meridional and vertical velocity. The three velocity components has to be scaled by a constant factor to enhance or decrease this constraint. It is recommended that this parameter is tuned by cross-validation. There are no tools currently in DIVAnd.jl to automate this process.
> 
> For the two dimensional case, the velocity has just two components

- [x] generate `zarr` collection.
- [x] calculate climatology.
- [x] export climatology as `zarr` & NetCDF.
- [x] `rsync` data to tube.
- [ ] write intake catalogue for BRAN2020
- [ ] clean up workflow, improve metadata, and document transfer approach.
- [ ] write some supporting docs to access the climatology.

**Comment by Thomas-Moore-Creative** [comment]
[output zarr, rechunked, and calculated climatology](https://github.com/CARSv2/cars-v2/commit/83ca878504f633059cc5a877f848986b57640830)

![Screenshot 2023-06-08 at 3 20 52 pm](https://github.com/CARSv2/cars-v2/assets/36463906/04024164-fec8-4cfd-bed5-49a139915bda)

**Comment by Thomas-Moore-Creative** [comment]
regional, 4D `zarr` collection on NCI scratch: `/scratch/xv83/tm4888/zarr_collections/BRAN2020/AUSregion.BRAN2020.month.UV.zarr`

**Comment by Thomas-Moore-Creative** [comment]
regional climatology of BRAN2020 U & V currents
![Screenshot 2023-06-15 at 1 49 48 pm](https://github.com/CARSv2/cars-v2/assets/36463906/2a223c58-b7d7-41f5-95e0-c9e71928805c)

**Comment by Thomas-Moore-Creative** [comment]
@ChrisC28 & @BecCowley 
I still need to document things better and possibly automate some things but as a start I've got a regional subset of both BRAN2020 u & v as well as the climatology over on **Tube** `/oa-decadal-climate/work/observations/CARSv2_ancillary/BRAN2020`

**Comment by ChrisC28** [comment]
Thanks @Thomas-Moore-Creative . I'll push the cleaned Julia code to github to perform the mapping today or tomorrow and then we can sit down an workout how we might get the velocities into DIVAnd.

**Comment by ChrisC28** [comment]
OK, I've pushed the updated "working" (term used partially in jest) example to the repo. Apologies for the delay (struggling with the token security).

**Comment by Thomas-Moore-Creative** [comment]
I believe @ChrisC28 will be using the updated climatological currents coming from #24 - so closing this here.
