### ISSUE TITLE
Incorporate U and V (advective constraints) into basic DIVAnd example.

### ISSUE THREAD

**Issue by ChrisC28** [CARSv2/cars-v2#14]

**Comment by Thomas-Moore-Creative** [comment]
@ChrisC28 - is there a "most recent" version of the DIVAns mapping code that the BRAN2020 advective constraints could be applied to?

**Comment by Thomas-Moore-Creative** [comment]
just a little ping on this @ChrisC28 - is there a "most recent" version of the DIVAnd mapping code that the BRAN2020 advective constraints could be applied to?

**Comment by ChrisC28** [comment]
Sorry to be late @Thomas-Moore-Creative this fell off my plate. I'm get a notebook on github shortly after lunchtime.

**Comment by Thomas-Moore-Creative** [comment]
- [ ] get @ChrisC28's example running locally
- [ ] get U/V constraints into correct format for `diva3d` call
- [ ] try to run `diva3d` with some BRAN2020 u/v constraints

**Comment by Thomas-Moore-Creative** [comment]
@ChrisC28  - any idea / recollection on how long the main `DIVAnd` call took on Tube?
```
 dbinfo = diva3d((Float64.(lonr),Float64.(latr),Float64.(depthr),TS),
    (Float64.(longitude),Float64.(latitude),Float64.(depth),time_dates), Float64.(temperature),
    len, epsilon2,
    filename,varname,
    bathname=bathname,
    plotres = plotres,
    mask = mask,
    moddim = zeros(Float64,4 - 1),
    fitcorrlen = false,
    niter_e = 2,
    ncvarattrib = ncvarattrib,
    ncglobalattrib = ncglobalattrib,
    surfextend = true
    );
```
Close to having your example running locally on my M2 laptop - but trying to get a feel for how long it will take?

**Comment by ChrisC28** [comment]
Can't remember exactly. However, it's a "push the button and go have lunch" type calculation

**Comment by Thomas-Moore-Creative** [comment]
> Can't remember exactly. However, it's a "push the button and go have lunch" type calculation

luckily it's almost noon!

`Julia` noob here will start to remember to use the `@time` macro.

**Comment by Thomas-Moore-Creative** [comment]
@ChrisC28 - I'm able to run things locally and I'm assuming it's not unexpected that some depths / months have "hot spots" - and that your run shows similar things given this is still very much an example, un-tuned test run?



![Image](https://github.com/CARSv2/cars-v2/assets/36463906/b6c25dd3-1504-4d39-98e6-d61a29118925)

**Comment by Thomas-Moore-Creative** [comment]
# get U/V constraints into correct format for `diva3d` call

- [ ] crop
- [ ] regrid 
- [ ] interpolate onto standard levels

**Comment by Thomas-Moore-Creative** [comment]
### progress through regridding BRAN onto DIVAnd grid
![Screenshot 2023-07-31 at 5 29 02 pm](https://github.com/CARSv2/cars-v2/assets/36463906/d3ce534e-435a-42bb-8091-da256530a087)

**Comment by Thomas-Moore-Creative** [comment]
@ChrisC28 has completed this task!
