### ISSUE TITLE
Code up workflow for quick, "local" download of WOD required for CARSv2

### ISSUE THREAD

**Issue by Thomas-Moore-Creative** [CARSv2/cars-v2#19]
#### requirements
- years: 2000 onward
- platforms: all

**Comment by BecCowley** [comment]
@Thomas-Moore-Creative I have copied IQuOD files onto Gadi and have been able to read them and plot very quickly with NCI VM 2 cores. Much quicker than files located on Bowen storage and trying to use code sitting on tube-hba which is located in Hobart.

**Comment by Thomas-Moore-Creative** [comment]
Nice work @BecCowley

It's always exciting when you get your compute and your data right next to each other.

Don't get me started on what has happened to Bowen storage.

**Comment by Thomas-Moore-Creative** [comment]
@BecCowley (and @ChrisC28 ) - so do we think this issue is resolved?  We plan to bring WOD data in via `Gadi` and then can transfer to other platforms / locations as needed?  

- How big is "everything" WOD? 
- What is the list of platforms / locations we'll need to get the data to?

Assume list includes machines on site in Hobart?  Do we need data on Canberra Bowen to utilise CSIRO HPC?

**Comment by BecCowley** [comment]
Might be useful: argopy libraries use DataFetcher
https://github.com/euroargodev/argopy

**Comment by Thomas-Moore-Creative** [comment]
looks like, for now, @ChrisC28 has WOD2018 downloaded - https://github.com/CARSv2/cars-v2/issues/20#issuecomment-2111431289

**Comment by Thomas-Moore-Creative** [comment]
Closing this as @ChrisC28 completed
