### ISSUE TITLE
Searchable database for CODA

### ISSUE THREAD

**Issue by ChrisC28** [CARSv2/cars-v2#22]
Can we produce a searchable database for CODA? 

Issues to think about: 

- File format? Parquet? 
- Do we need to change the format or structure of the underlying CODA netcdf files (ie. is grouped yearly, by data originator and platform optimal for a searchable database? Would day-by-day or profile-by-profile work better?)
- How do we interogate? Polars? https://docs.pola.rs/

**Comment by Thomas-Moore-Creative** [comment]
Yesterday @ChrisC28 & @BecCowley we discussed this issue and talked about the following use case:

for all the ARGO (or CTD, or ... ) *data type* in a given *region*, over a *time period*, over a *depth range*, with given *variable* . . 

- quickly and easily make plots of where this data is
- grab all the data, record by record in a tabular format
- grab all the data as analysis-ready profiles

**Comment by Thomas-Moore-Creative** [comment]
starting with 2012 as an example: `/g/data/es60/users/thomas_moore/CODA/2012`
```
(base) tm4888@gadi-login-04 /g/data/es60/users/thomas_moore/CODA/2012 ls -l
total 119157796
-rw-rw-r-- 1 tm4888 es60     2621287 May 28 16:13 AIMS_CODA_2012_ctd.nc
-rw-rw-r-- 1 tm4888 es60    39738448 May 21 10:40 MNF_CODA_2012_ctd.nc
-rw-rw-r-- 1 tm4888 es60    49086082 May 21 10:39 RAN_CODA_2012_ctd.nc
-rw-rw-r-- 1 tm4888 es60 15309446859 May 15 21:31 WOD2018_CODA_2012_ctd.nc
-rw-rw-r-- 1 tm4888 es60 33029760782 May 15 23:46 WOD2018_CODA_2012_gld.nc
-rw-rw-r-- 1 tm4888 es60    85704294 May 15 23:05 WOD2018_CODA_2012_mrb.nc
-rw-rw-r-- 1 tm4888 es60   129700151 May 15 21:21 WOD2018_CODA_2012_osd.nc
-rw-rw-r-- 1 tm4888 es60 71305005747 May 15 22:54 WOD2018_CODA_2012_pfl.nc
-rw-rw-r-- 1 tm4888 es60  2066312325 May 15 21:35 WOD2018_CODA_2012_xbt.nc
```

**Comment by Thomas-Moore-Creative** [comment]
Heya @ChrisC28 do variables like `Temperature_WODflag` need to be `float64`?
![CleanShot 2024-08-14 at 15 01 21@2x](https://github.com/user-attachments/assets/1a4865b4-8f09-4399-a5f5-629722c9b4fb)

**Comment by Thomas-Moore-Creative** [comment]
@ChrisC28 ... can you see / reach `/oa-decadal-climate/work/observations/CARSv2_ancillary/CODA/CODAv1/`?

`tube` locked up on me and then suddenly everything from `/oa-decadal-climate/work/` was "gone"?

**Comment by BecCowley** [comment]
The CODA netcdf files contain different numbers of variables for each type (eg, WOD files have more variables than MNF files). 
When converting to parquet formats, the schemas will be different for each and with my small amount of knowledge on parquet collections, that will mean separate loading. Or, will we fill in variables with empty where they are missing (eg, WOD_id filled with NaN in MNF files) to make a consistent and complete dataset? 
Thoughts @Thomas-Moore-Creative, @ChrisC28?

**Comment by Thomas-Moore-Creative** [comment]
> Or, will we fill in variables with empty where they are missing (eg, WOD_id filled with NaN in MNF files) to make a consistent and complete dataset?

@BecCowley . . .  Does this depend on how much ( everything? one platform? etc ) is stored in the CODA PQ files?  My thinking has been that, at some level, this will involve padding out tables with `NaN`'s?

**Comment by BecCowley** [comment]
@Thomas-Moore-Creative it does depend on what is stored in the PQ files. If we have a template of required variables, then some will be padded with NaNs where the information doesn't exist. A template for different data types will help to minimise the number of empty variables.

**Comment by Thomas-Moore-Creative** [comment]
Dumb question - but isn't the final CODA schema the template for everything?  Or is that what we need in tabular form?

**Comment by BecCowley** [comment]
There are no dumb questions.
Some examples: 

- In the XBT files there is a depth correction variable. This isn't included in other data types. 
- Salinity doesn't exist for some instruments 
- Within instrument groups: the WOD files have additional metadata that the MNF or AIMS etc files might not have, eg a WOD accession number, instrument model

In our CODA nc files, if the variable or metadata doesn't appear in the orignal file, it isn't in the CODA nc file. In the PQ file, do we fill in these with NaN or have separate files without the missing information?

**Comment by Thomas-Moore-Creative** [comment]
> There are no dumb questions. Some examples:
> 
> * In the XBT files there is a depth correction variable. This isn't included in other data types.
> * Salinity doesn't exist for some instruments
> * Within instrument groups: the WOD files have additional metadata that the MNF or AIMS etc files might not have, eg a WOD accession number, instrument model
> 
> In our CODA nc files, if the variable or metadata doesn't appear in the orignal file, it isn't in the CODA nc file. In the PQ file, do we fill in these with NaN or have separate files without the missing information?

My view is - **importantly subject to performance and storage limits** - we want **ALL** metadata in the PQ files as columns.  AKA - let's not worry about lots and lots of `NaN` padding until we can prove a PQ & Polars approach can't deal with it for important use cases.

Another dumb question - do we have the current "everything that could be in CODA" schema listed anywhere?

**Comment by Thomas-Moore-Creative** [comment]
Some notes:
In the current example we are using a single `NetCDF` file `WOD_CODA_2005_pfl.nc` which is: `6.1GB`

**Comment by Thomas-Moore-Creative** [comment]
See notes above:

`filtered_pdf = pdf.filter((pl.col('Temperature') >= 65))`
![CleanShot 2024-10-23 at 10 41 54@2x](https://github.com/user-attachments/assets/4ca943ca-bfe3-4136-b203-c29976833ebf)
```
CPU times: user 272 ms, sys: 30.2 ms, total: 302 ms
Wall time: 204 ms
```
