### ISSUE TITLE
Remove rows where all variables are padded NaN's

### ISSUE THREAD

**Issue by Thomas-Moore-Creative** [CARSv2/cars-v2#26]
As discussed @ChrisC28 & @BecCowley

**Comment by BecCowley** [comment]
Small dataset of CTDs from WOD and MNF are located in /oa-decadal-climate/work/observations/CARSv2_ancillary/CODA/CODAv1/testdups

**Comment by Thomas-Moore-Creative** [comment]
Now that I have my head around this I believe this is as simple as providing:

`df.dropna(subset=list_of_all_possible_variables).reset_index(drop=True)` (or `ddf` or `pq` equivalent)

as early in the workflow as possible.

@BecCowley - I'm still working with the single `WOD_CODA_2005_pfl.nc`.  I'll make a separate issue for file for testing testing `/oa-decadal-climate/work/observations/CARSv2_ancillary/CODA/CODAv1/testdups` with PQ workflow.
